    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/style.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/style2.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/style84e2.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/bootstrap84e2.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/fonts.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/nucleo.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/portal.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/whatsapp.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/dashicons.min84fc.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/swiper.min48f5.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/sweetalert2.min.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/buttons.min84fc.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/frontend-lite.minf3b2.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/widget-icon-box.min.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/elementor/assets/css/pa-frontend.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/elementor/assets/css/pa-frontend-595b41f31.min9b85.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/elementor/assets/css/pa-frontend-757c5b548.mina9c6.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/unlimited-elements-for-elementor/assets_libraries/lity/lity.min.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/unlimited-elements-for-elementor/assets_libraries/font-awesome5/css/fontawesome-all.min.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/unlimited-elements-for-elementor/assets_libraries/font-awesome5/css/fontawesome-v4-shims.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/elementor/assets/lib/animations/animations.minf3b2.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/elementor/assets/lib/swiper/css/swiper.min48f5.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/frontend-lite.min.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/essential-addons-for-elementor-lite/assets/front-end/css/view/general.min7404.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/elementor/assets/lib/eicons/css/elementor-icons.min7bb8.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/premium-addons-for-elementor/assets/frontend/min-css/premium-addons.min221e.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/premium-addons-for-elementor/assets/frontend/min-css/prettyphoto.min221e.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/premium-addons-for-elementor/assets/frontend/min-css/slick.min221e.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/unlimited-elements-for-elementor/assets_libraries/owl-carousel-new/assets/fontawesome-all.min.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/unlimited-elements-for-elementor/assets_libraries/owl-carousel-new/assets/fontawesome-v4-shims.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/unlimited-elements-for-elementor/assets_libraries/owl-carousel-new/assets/lity.min.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/unlimited-elements-for-elementor/assets_libraries/owl-carousel-new/assets/owl.carousel.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/plugins/unlimited-elements-for-elementor/assets_libraries/owl-carousel-new/fontawesome-all.min.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/style23.css">
    <link rel="stylesheet" href="<?php echo BASE_URL; ?>assets/css/nosotrso.css">